const C={
'roi-calculator':{fields:[['Investment cost','investment'],['Final return','return']],formula:'ROI = ((Final Return − Investment Cost) ÷ Investment Cost) × 100',fn:v=>{let p=v.return-v.investment;return [p/v.investment*100,`Net return: ${money(p)}`]}},
'investment-roi':{fields:[['Initial investment','initial'],['Final value','final'],['Income received','income']],formula:'ROI = ((Final Value + Income − Initial Investment) ÷ Initial Investment) × 100',fn:v=>{let p=v.final+v.income-v.initial;return [p/v.initial*100,`Total gain: ${money(p)}`]}},
'marketing-roi':{fields:[['Marketing cost','cost'],['Attributable return','return']],formula:'Marketing ROI = ((Attributable Return − Marketing Cost) ÷ Marketing Cost) × 100',fn:v=>{let p=v.return-v.cost;return [p/v.cost*100,`Net return: ${money(p)}`]}},
'manufacturing-roi':{fields:[['Manufacturing investment','investment'],['Annual additional profit','profit'],['Annual operating savings','savings']],formula:'ROI = ((Annual Profit + Annual Savings − Investment) ÷ Investment) × 100',fn:v=>{let b=v.profit+v.savings;return [(b-v.investment)/v.investment*100,`Annual benefit: ${money(b)} · Payback: ${v.investment/b? (v.investment/b).toFixed(2):'—'} years`]}},
'machine-roi':{fields:[['Machine cost','cost'],['Annual additional profit','profit'],['Annual labor / operating savings','savings']],formula:'ROI = ((Annual Profit + Annual Savings − Machine Cost) ÷ Machine Cost) × 100',fn:v=>{let b=v.profit+v.savings;return [(b-v.cost)/v.cost*100,`Annual benefit: ${money(b)} · Payback: ${v.cost/b? (v.cost/b).toFixed(2):'—'} years`]}},
'packaging-roi':{fields:[['Packaging investment','investment'],['Annual labor savings','labor'],['Annual material savings','material'],['Annual additional profit','profit']],formula:'ROI = ((Annual Benefit − Investment) ÷ Investment) × 100',fn:v=>{let b=v.labor+v.material+v.profit;return [(b-v.investment)/v.investment*100,`Annual benefit: ${money(b)} · Payback: ${v.investment/b? (v.investment/b).toFixed(2):'—'} years`]}},
'equipment-roi':{fields:[['Equipment cost','cost'],['Annual additional profit','profit'],['Annual savings','savings']],formula:'ROI = ((Annual Profit + Annual Savings − Equipment Cost) ÷ Equipment Cost) × 100',fn:v=>{let b=v.profit+v.savings;return [(b-v.cost)/v.cost*100,`Annual benefit: ${money(b)} · Payback: ${v.cost/b? (v.cost/b).toFixed(2):'—'} years`]}},
'employee-roi':{fields:[['Annual employee cost','cost'],['Annual value generated','value']],formula:'Employee ROI = ((Value Generated − Employee Cost) ÷ Employee Cost) × 100',fn:v=>{let p=v.value-v.cost;return [p/v.cost*100,`Net value: ${money(p)}`]}},
'warehouse-roi':{fields:[['Warehouse investment','investment'],['Annual labor savings','labor'],['Annual operating savings','savings'],['Annual additional profit','profit']],formula:'ROI = ((Annual Benefit − Investment) ÷ Investment) × 100',fn:v=>{let b=v.labor+v.savings+v.profit;return [(b-v.investment)/v.investment*100,`Annual benefit: ${money(b)} · Payback: ${v.investment/b? (v.investment/b).toFixed(2):'—'} years`]}},
'inventory-roi':{fields:[['Gross profit','profit'],['Average inventory investment','inventory']],formula:'Inventory ROI = (Gross Profit ÷ Average Inventory) × 100',fn:v=>[v.profit/v.inventory*100,`Gross profit per $1 of inventory: ${money(v.profit/v.inventory)}`]}
};
const slug=document.body.dataset.calculator,c=C[slug];
const fields=document.querySelector('#fields');fields.innerHTML=c.fields.map(([l,id])=>`<div class="field"><label for="${id}">${l}</label><input id="${id}" type="number" min="0" step="any" placeholder="0"></div>`).join('');
document.querySelector('#formula').textContent=c.formula;
function money(n){return '$'+Number(n).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})}
document.querySelector('#calculatorForm').addEventListener('submit',e=>{e.preventDefault();const v={};c.fields.forEach(([,id])=>v[id]=Number(document.getElementById(id).value));const required=c.fields[0][1];if(!Number.isFinite(v[required])||v[required]<=0){document.querySelector('#error').style.display='block';document.querySelector('#error').textContent='Enter a valid positive value for the primary investment or cost.';return}try{const [r,s]=c.fn(v);document.querySelector('#result').textContent=r.toFixed(2)+'%';document.querySelector('#resultSub').textContent=s;document.querySelector('#error').style.display='none'}catch{document.querySelector('#error').style.display='block'}});
